language: python
sudo: required
services:
  - docker
cache: pip
os:
  - linux
python:
  - "3.6"
script:
  - pip install -U pip pipenv
  - pipenv install --dev
  - pipenv run nose2 --with-coverage --coverage-report=term-missing
after_success:
  - coveralls
  - "./tests/lint.sh funding"
  - "./tests/style.sh funding"
  - "./tests/type-check.sh funding"
  - if [[ $TRAVIS_BRANCH == $DOCUMENTATION_BRANCH ]]; then ./update-docs.sh; fi
